version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: upright_cleaning_services_DB
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: uprightcleaningservices
    environment:
      DB_URL: jdbc:mysql://mysql:3306/upright_cleaning_services_DB
      DB_USERNAME: root
      DB_PASSWORD: password
    ports:
      - "8000:8080"
    depends_on:
      - mysql
