@startuml
   title: Authentication Diagram
  participant User
  participant SpringBootApp
  participant AuthenticationProvider

  User -> SpringBootApp: Login request (username, password)
  activate SpringBootApp
  SpringBootApp -> AuthenticationProvider: Authenticate (username, password)
  alt Successful Authentication
    AuthenticationProvider --> SpringBootApp: Authentication success (user object)
    activate SpringBootApp
    SpringBootApp -> User: Login successful (JWT token)
  else Authentication Failure
    AuthenticationProvider --> SpringBootApp: Authentication failure (reason)
    activate SpringBootApp
    SpringBootApp -> User: Login failed (error message)
  end
  deactivate SpringBootApp
@enduml



